---
title: "Dashboard Example"
author: "Nils Indreiten"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 3
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
pacman::p_load(flexdashboard,ggplot2,plotly,tidyverse,plyr,data.table,crosstalk)
d <- sample_n(diamonds, size=1000, replace = T)
d <- crosstalk::SharedData$new(d)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Diamond Chart by Colour

```{r}
p<-  ggplot(d,aes(color, fill=cut))+
  geom_bar()+theme_classic()+ylab("Count")+xlab("Color")+theme(legend.title=element_blank())
ggplotly(p)
```

> Source: Diamonds dataset (random sample of 1000 diamonds)

Column {data-width=350}
-----------------------------------------------------------------------

### Diamond Frequency and Price by Cut

```{r, message=FALSE, error=FALSE}
p <- ggplot(d,aes(price,colour=cut))+
            geom_freqpoly(binwidth=500)+theme_minimal()+ylab("Count")+xlab("Price")
ggplotly(p)
```



### Carat and Price Relationship

```{r}
p <- ggplot(d,aes(carat,price))+geom_point()+geom_smooth(se=TRUE)+theme_minimal()+ylab("Price")+xlab("Carat")
ggplotly(p)
```


